/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubdomainsRouteImport } from './routes/subdomains'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as IssuesRouteImport } from './routes/issues'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'

const SubdomainsRoute = SubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const IssuesRoute = IssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/import': typeof ImportRoute
  '/issues': typeof IssuesRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/subdomains': typeof SubdomainsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/import': typeof ImportRoute
  '/issues': typeof IssuesRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/subdomains': typeof SubdomainsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/import': typeof ImportRoute
  '/issues': typeof IssuesRoute
  '/scans': typeof ScansRoute
  '/settings': typeof SettingsRoute
  '/subdomains': typeof SubdomainsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/import'
    | '/issues'
    | '/scans'
    | '/settings'
    | '/subdomains'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/import'
    | '/issues'
    | '/scans'
    | '/settings'
    | '/subdomains'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/import'
    | '/issues'
    | '/scans'
    | '/settings'
    | '/subdomains'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  ImportRoute: typeof ImportRoute
  IssuesRoute: typeof IssuesRoute
  ScansRoute: typeof ScansRoute
  SettingsRoute: typeof SettingsRoute
  SubdomainsRoute: typeof SubdomainsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subdomains': {
      id: '/subdomains'
      path: '/subdomains'
      fullPath: '/subdomains'
      preLoaderRoute: typeof SubdomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/issues': {
      id: '/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof IssuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  ImportRoute: ImportRoute,
  IssuesRoute: IssuesRoute,
  ScansRoute: ScansRoute,
  SettingsRoute: SettingsRoute,
  SubdomainsRoute: SubdomainsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
